jobs:
  Check:
    name: Check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Install JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.4
    - continue-on-error: true
      name: Code checks
      run: ./gradlew check
    strategy:
      matrix:
        java_version:
        - 17
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Install JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.4
    - continue-on-error: true
      name: Build project
      run: ./gradlew assembleDebug
    strategy:
      matrix:
        java_version:
        - 17
name: PullRequest
on:
  repository_dispatch:
    types: trigger-ga___Android-CI.yml
